site_name: FabLab Kuriyama Lab Site

site_description: FabLab Kuriyama

site_author: Toshiki Tsuchiyama, Atsufumi Suzuki
docs_dir: docs
site_dir: _site
copyright: Creative Commons Attribution Non Commercial
theme:
  icon:
    logo: material/school
  favicon: images/favicon.svg
  name: material
  # see https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
  palette:
    primary: "deep"
    accent: "indigo"
  font:
    # false
    text: "Ubuntu"
    code: "Ubuntu Mono"
  feature:
    tabs: true

extra:
  social:
    - type: "github"
      link: "https://github.com/academany"
    - type: "twitter"
      link: "https://twitter.com/fabacademany"
    - type: "linkedin"
      link: "https://linkedin.com/in/academany"
    - type: "instagram"
      link: "https://instagram.com/fabacademany"

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

